### ISSUE TITLE
Get Admin approval to link Shopify to this GitHub repo

### ISSUE THREAD

**Issue by thetwopct** [cncf/shopify-theme#1]
![CleanShot 2022-11-07 at 15 59 55@2x](https://user-images.githubusercontent.com/10615884/200269686-48522dc7-e01d-4fc0-ab61-4120e352017e.png)

**Comment by amye** [comment]
You look good to go here? Ping me if not.

**Comment by thetwopct** [comment]
@amye Yes got it, Chris Ab approved it just before your message, thanks so much!
